project:
  type: website
  output-dir: docs
  render:
    - GoM-2023-amplicons.qmd
    - gulf-2023-amplicon-analysis.qmd

execute:
  eval: false

website:
  title: "Diversity of microeukaryotes in the Gulf"
  navbar:
    left:
      - href: GoM-2023-amplicons.qmd
        text: Home
      - href: gulf-2023-amplicon-analysis.qmd
        text: Data analysis

format:
  html:
    theme: flatly
    toc: true
    toc-location: left
    number-sections: true
    number-depth: 3
    



